name = "Slim"
license = "MIT"
licenselink = "https://github.com/crup/slim-coder/blob/master/LICENSE.md"
description = "A slim minimal theme for Hugo."
homepage = "https://github.com/crup/slim-coder"
tags = ["minimal", "clean", "neat", "black white", "blog"]
features = ["blog"]
min_version = 0.13

[author]
    name = "Rajender Joshi"
    homepage = "https://2km.co"
